---
title: "DataAnalysis"
author: Elizabeth Orozco & Alex Stadlinger
format: pdf
editor: visual
---

## Load in packages and unzip files

```{r}
#load in required packages
library(tidyr)
library(dplyr)
library(ggplot2)
library(patchwork)
```

```{r}
#unzip rodent activity file
# unzip("edi.2200.1.zip")
```

## Read in required files

```{r}
#read in rodent activity file
rodent_data <- read.csv("Rodent_activity.csv")
```

```{r}
#read in trapping data file
trapping_data <- read.csv("Trapping.csv")
```

```{r}
#read in vegetation cover data file
vegetation_data <- read.csv("Vegetation_cover.csv")
```

```{r}
#read in seed predation data
seed_predation_data <- read.csv("Seed_predation.csv")
```

## Clean up files

```{r}
#separate data in trapping_data
colnames(trapping_data)

trapping_separated <- trapping_data %>%
  separate(col = Trap_day.Lynx.Habitat.Plot.Trap.Species.Working, 
           into = c("Trap_day", "Lynx", "Habitat", "Plot", "Trap", "Species", "Working"), 
           sep = ";")
```

```{r}
#separate data in vegetation_data
colnames(vegetation_data)

vegetation_separated <- vegetation_data %>%
  separate(col = Lynx.Plot.Habitat.Tree.Shrub.Rock, 
           into = c("Lynx", "Plot", "Habitat", "Tree", "Shrub", "Rock"), 
           sep = ";")
```

```{r}
#separate seed predation data
colnames(seed_predation_data)

seed_predation_separated <- seed_predation_data %>%
  separate(col = Lynx.Habitat.Plot.Microhabitat.Code.CAM.Seeds_left0.Seeds_left1.Seeds_predated1.Seeds_left2.Seeds_oredated2.Seeds_left3.Seeds_predated3.Seeds_left4.Seeds_predated4.Seeds_left5.Seeds_predated5.Seeds_predated_total, 
           into = c("Lynx", "Habitat", "Plot", "Microhabitat", "Code", "CAM", "Seeds_left0", "Seeds_left1", "Seeds_predated1", "Seeds_left2", "Seeds_oredated2", "Seeds_left3", "Seeds_predated3", "Seeds_left4", "Seeds_predated4", "Seeds_left5", "Seeds_predated5", "Seeds_predated_total"), 
           sep = ";")
```

```{r}
#make seed predated total column numeric
seed_predation_separated$Seeds_predated_total <- as.numeric(seed_predation_separated$Seeds_predated_total)
```

## Graphs!

```{r}
#plotting seed predation total against lynx presence
ggplot(data = seed_predation_separated, aes(x = Lynx, y = Seeds_predated_total)) +
  geom_col()
```

```{r}
#plotting seed predation total as a function of habitat type
ggplot(data = seed_predation_separated, aes(x = Habitat, y = Seeds_predated_total)) +
  geom_col()
```

```{r}
#plotting seed predation total as a function of microhabitat
ggplot(data = seed_predation_separated, aes(x = Microhabitat, y = Seeds_predated_total)) +
  geom_col()
```

```{r}
#graph 1: lynx = 1, microhabitat = open
lynx_open <- filter(seed_predation_separated, Lynx == "1", Microhabitat == "Open")

g1 <- ggplot(data = lynx_open, aes(x = Habitat, y = Seeds_predated_total, fill = Habitat)) + 
  geom_col()
  labs(x = "Microhabitat",
       y = "Total Number of Seeds Predated",
       title = "Lynx Present")
```

```{r}
#graph 2: lynx = 1, microhabitat = rock
lynx_rock <- filter(seed_predation_separated, Lynx == "1", Microhabitat == "Rock")

g2 <- ggplot(data = lynx_rock, aes(x = Habitat, y = Seeds_predated_total, fill = Habitat)) +
  geom_col() + 
  labs(x = "Microhabitat",
       y = "Total Number of Seeds Predated",
       title = "Lynx Present")
```

```{r}
#graph 3: lynx = 1, microhabitat = shrub
lynx_shrub <- filter(seed_predation_separated, Lynx == "1", Microhabitat == "Shrub")

g3 <- ggplot(data = lynx_shrub, aes(x = Habitat, y = Seeds_predated_total, fill = Habitat)) +
  geom_col() + 
  labs(x = "Microhabitat",
       y = "Total Number of Seeds Predated",
       title = "Lynx Present")
```

```{r}
#graph 4: lynx = 0, microhabitat = open
noLynx_open <- filter(seed_predation_separated, Lynx == "0", Microhabitat == "Open")

g4 <- ggplot(data = lynx_open, aes(x = Habitat, y = Seeds_predated_total, fill = Habitat)) +
  geom_col() + 
  labs(x = "Microhabitat",
       y = "Total Number of Seeds Predated",
       title = "No Lynx Present")
```

```{r}
#graph 5: lynx = 0, microhabitat = rock
noLynx_rock <- filter(seed_predation_separated, Lynx == "0", Microhabitat == "Rock")

g5 <- ggplot(data = noLynx_rock, aes(x = Habitat, y = Seeds_predated_total, fill = Habitat)) +
  geom_col() + 
  labs(x = "Microhabitat",
       y = "Total Number of Seeds Predated",
       title = "No Lynx Present")
```

```{r}
#graph 6: lynx = 0, microhabitat = shrub
noLynx_shrub <- filter(seed_predation_separated, Lynx == "0", Microhabitat == "Shrub")

g6 <- ggplot(data = noLynx_shrub, aes(x = Habitat, y = Seeds_predated_total, fill = Habitat)) +
  geom_col() + 
  labs(x = "Microhabitat",
       y = "Total Number of Seeds Predated",
       title = "No Lynx Present")
```

```{r}
#open
(g1 + g4) + plot_annotation(
  title = 'Microhabitat: Open')
```

```{r}
#rock
(g2 + g5) + plot_annotation(
  title = 'Microhabitat: Rock')
```

```{r}
#shrub
(g3 + g6) + plot_annotation(
  title = 'Microhabitat: Shrub')
```
